[package]
name = "quill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphul = "0.4.5"
serde_json = "1.0.91"
tokio = "1.24.1"